name: CI

on: [ push, pull_request ]

jobs:
 tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [ '7.4', '8.1', '8.3' ]

    name: PHP ${{ matrix.php }}
    steps:
      - uses: actions/checkout@v3

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none

      - name: Install Dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run Linting
        run: composer lint

      - name: PHPUnit Tests
        run: composer test

      - name: Google Chat Notification
        uses: Co-qn/google-chat-notification@releases/v1
        with:
          name: Build
          url: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
          status: ${{ job.status }}
        if: always()
