name: CI

on: [ push, pull_request ]

jobs:
 tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [ '7.4', '8.3' ]

    name: PHP ${{ matrix.php }}
    steps:
      - uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: ${{ matrix.php }}

      - uses: actions/checkout@v3

      - uses: php-actions/composer@v3

      - name: PHPUnit Tests
        uses: php-actions/phpunit@master
        with:
          php_version: ${{ matrix.php }}
          bootstrap: tests/bootstrap.php
          configuration: phpunit.xml

      - name: Google Chat Notification
        uses: Co-qn/google-chat-notification@releases/v1
        with:
          name: Build
          url: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
          status: ${{ job.status }}
        if: always()
